### ISSUE TITLE
Prevent continuous opening of the save dialog on unsaved files

### ISSUE THREAD

**Issue by hkupitz** [pinussilvestrus/camunda-modeler-autosave-plugin#69]
__Describe the Bug__

When having the plugin's autosave functionality enabled, it repeatedly opens new instances of the save dialog for unsaved files. If the plugin is set to autosave every few seconds this makes it pretty hard to actually save a file.

__Steps to Reproduce__

1. Disable the autosave functionality.
2. Create a new diagram and *don't save it*.
3. Enable the autosave functionality.
4. Click on the diagram space at least once.
5. Wait.

__Expected Behavior__

Before kicking in the plugin should either wait for the file to be saved for the first time (might be a bit unsafe) or simply only open the save dialog once.

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.11.1
- Installed plug-ins: Camunda Modeler Autosave Plugin

**Comment by pinussilvestrus** [comment]
Thanks for reporting. 👍
